"use client";

import type { Dispatch, SetStateAction } from "react";
import type { DesignerCanvasSnapshot } from "@/components/designer/designer-model";

export type ApplyCanvasSnapshotDeps = {
  setTitle: Dispatch<SetStateAction<DesignerCanvasSnapshot["title"]>>;
  setFormChildren: Dispatch<SetStateAction<DesignerCanvasSnapshot["formChildren"]>>;
  setHeaderButtons: Dispatch<SetStateAction<DesignerCanvasSnapshot["headerButtons"]>>;
  setButtonBox: Dispatch<SetStateAction<DesignerCanvasSnapshot["buttonBox"]>>;
  setStatusbarField: Dispatch<SetStateAction<DesignerCanvasSnapshot["statusbarField"]>>;
  setStatusbarVisible: Dispatch<SetStateAction<DesignerCanvasSnapshot["statusbarVisible"]>>;
  setFormCanCreate: Dispatch<SetStateAction<DesignerCanvasSnapshot["formCanCreate"]>>;
  setFormCanEdit: Dispatch<SetStateAction<DesignerCanvasSnapshot["formCanEdit"]>>;
  setFormCanDelete: Dispatch<SetStateAction<DesignerCanvasSnapshot["formCanDelete"]>>;
  setFormCanDuplicate: Dispatch<SetStateAction<DesignerCanvasSnapshot["formCanDuplicate"]>>;
  setListColumns: Dispatch<SetStateAction<DesignerCanvasSnapshot["listColumns"]>>;
  setListDecorationDanger: Dispatch<SetStateAction<DesignerCanvasSnapshot["listDecorationDanger"]>>;
  setListDecorationInfo: Dispatch<SetStateAction<DesignerCanvasSnapshot["listDecorationInfo"]>>;
  setListDecorationMuted: Dispatch<SetStateAction<DesignerCanvasSnapshot["listDecorationMuted"]>>;
  setListCanCreate: Dispatch<SetStateAction<DesignerCanvasSnapshot["listCanCreate"]>>;
  setListCanEdit: Dispatch<SetStateAction<DesignerCanvasSnapshot["listCanEdit"]>>;
  setListCanDelete: Dispatch<SetStateAction<DesignerCanvasSnapshot["listCanDelete"]>>;
  setListMultiEdit: Dispatch<SetStateAction<DesignerCanvasSnapshot["listMultiEdit"]>>;
  setListDefaultOrder: Dispatch<SetStateAction<DesignerCanvasSnapshot["listDefaultOrder"]>>;
  setViewSample: Dispatch<SetStateAction<DesignerCanvasSnapshot["viewSample"]>>;
  setSearchFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["searchFields"]>>;
  setSearchFilters: Dispatch<SetStateAction<DesignerCanvasSnapshot["searchFilters"]>>;
  setSearchGroupByFilters: Dispatch<SetStateAction<DesignerCanvasSnapshot["searchGroupByFilters"]>>;
  setKanbanFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["kanbanFields"]>>;
  setKanbanGroupBy: Dispatch<SetStateAction<DesignerCanvasSnapshot["kanbanGroupBy"]>>;
  setKanbanCanCreate: Dispatch<SetStateAction<DesignerCanvasSnapshot["kanbanCanCreate"]>>;
  setKanbanQuickCreate: Dispatch<SetStateAction<DesignerCanvasSnapshot["kanbanQuickCreate"]>>;
  setCalendarDateStart: Dispatch<SetStateAction<DesignerCanvasSnapshot["calendarDateStart"]>>;
  setCalendarDateStop: Dispatch<SetStateAction<DesignerCanvasSnapshot["calendarDateStop"]>>;
  setCalendarColor: Dispatch<SetStateAction<DesignerCanvasSnapshot["calendarColor"]>>;
  setCalendarMode: Dispatch<SetStateAction<DesignerCanvasSnapshot["calendarMode"]>>;
  setCalendarFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["calendarFields"]>>;
  setGraphType: Dispatch<SetStateAction<DesignerCanvasSnapshot["graphType"]>>;
  setGraphFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["graphFields"]>>;
  setPivotFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["pivotFields"]>>;
  setMapResPartner: Dispatch<SetStateAction<DesignerCanvasSnapshot["mapResPartner"]>>;
  setMapRouting: Dispatch<SetStateAction<DesignerCanvasSnapshot["mapRouting"]>>;
  setMapFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["mapFields"]>>;
  setActivityFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["activityFields"]>>;
  setGanttDateStart: Dispatch<SetStateAction<DesignerCanvasSnapshot["ganttDateStart"]>>;
  setGanttDateStop: Dispatch<SetStateAction<DesignerCanvasSnapshot["ganttDateStop"]>>;
  setGanttGroupBy: Dispatch<SetStateAction<DesignerCanvasSnapshot["ganttGroupBy"]>>;
  setGanttColor: Dispatch<SetStateAction<DesignerCanvasSnapshot["ganttColor"]>>;
  setGanttProgress: Dispatch<SetStateAction<DesignerCanvasSnapshot["ganttProgress"]>>;
  setGanttDefaultScale: Dispatch<SetStateAction<DesignerCanvasSnapshot["ganttDefaultScale"]>>;
  setGanttDependencyField: Dispatch<SetStateAction<DesignerCanvasSnapshot["ganttDependencyField"]>>;
  setGanttFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["ganttFields"]>>;
  setCohortDateStart: Dispatch<SetStateAction<DesignerCanvasSnapshot["cohortDateStart"]>>;
  setCohortDateStop: Dispatch<SetStateAction<DesignerCanvasSnapshot["cohortDateStop"]>>;
  setCohortInterval: Dispatch<SetStateAction<DesignerCanvasSnapshot["cohortInterval"]>>;
  setCohortMode: Dispatch<SetStateAction<DesignerCanvasSnapshot["cohortMode"]>>;
  setCohortTimeline: Dispatch<SetStateAction<DesignerCanvasSnapshot["cohortTimeline"]>>;
  setCohortMeasure: Dispatch<SetStateAction<DesignerCanvasSnapshot["cohortMeasure"]>>;
  setGridRowField: Dispatch<SetStateAction<DesignerCanvasSnapshot["gridRowField"]>>;
  setGridColField: Dispatch<SetStateAction<DesignerCanvasSnapshot["gridColField"]>>;
  setGridMeasure: Dispatch<SetStateAction<DesignerCanvasSnapshot["gridMeasure"]>>;
  setGridAdjustment: Dispatch<SetStateAction<DesignerCanvasSnapshot["gridAdjustment"]>>;
  setGridDateStart: Dispatch<SetStateAction<DesignerCanvasSnapshot["gridDateStart"]>>;
  setGridDateStop: Dispatch<SetStateAction<DesignerCanvasSnapshot["gridDateStop"]>>;
  setGridFields: Dispatch<SetStateAction<DesignerCanvasSnapshot["gridFields"]>>;
  setArchOverride: Dispatch<SetStateAction<DesignerCanvasSnapshot["archOverride"]>>;
};

export function applyCanvasSnapshot(
  deps: ApplyCanvasSnapshotDeps,
  snapshot: DesignerCanvasSnapshot,
): void {
  deps.setTitle(snapshot.title);
  deps.setFormChildren(snapshot.formChildren);
  deps.setHeaderButtons(snapshot.headerButtons);
  deps.setButtonBox(snapshot.buttonBox);
  deps.setStatusbarField(snapshot.statusbarField);
  deps.setStatusbarVisible(snapshot.statusbarVisible);
  deps.setFormCanCreate(snapshot.formCanCreate);
  deps.setFormCanEdit(snapshot.formCanEdit);
  deps.setFormCanDelete(snapshot.formCanDelete);
  deps.setFormCanDuplicate(snapshot.formCanDuplicate);
  deps.setListColumns(snapshot.listColumns);
  deps.setListDecorationDanger(snapshot.listDecorationDanger);
  deps.setListDecorationInfo(snapshot.listDecorationInfo);
  deps.setListDecorationMuted(snapshot.listDecorationMuted);
  deps.setListCanCreate(snapshot.listCanCreate);
  deps.setListCanEdit(snapshot.listCanEdit);
  deps.setListCanDelete(snapshot.listCanDelete);
  deps.setListMultiEdit(snapshot.listMultiEdit);
  deps.setListDefaultOrder(snapshot.listDefaultOrder);
  deps.setViewSample(snapshot.viewSample);
  deps.setSearchFields(snapshot.searchFields);
  deps.setSearchFilters(snapshot.searchFilters);
  deps.setSearchGroupByFilters(snapshot.searchGroupByFilters);
  deps.setKanbanFields(snapshot.kanbanFields);
  deps.setKanbanGroupBy(snapshot.kanbanGroupBy);
  deps.setKanbanCanCreate(snapshot.kanbanCanCreate);
  deps.setKanbanQuickCreate(snapshot.kanbanQuickCreate);
  deps.setCalendarDateStart(snapshot.calendarDateStart);
  deps.setCalendarDateStop(snapshot.calendarDateStop);
  deps.setCalendarColor(snapshot.calendarColor);
  deps.setCalendarMode(snapshot.calendarMode);
  deps.setCalendarFields(snapshot.calendarFields);
  deps.setGraphType(snapshot.graphType);
  deps.setGraphFields(snapshot.graphFields);
  deps.setPivotFields(snapshot.pivotFields);
  deps.setMapResPartner(snapshot.mapResPartner);
  deps.setMapRouting(snapshot.mapRouting);
  deps.setMapFields(snapshot.mapFields);
  deps.setActivityFields(snapshot.activityFields);
  deps.setGanttDateStart(snapshot.ganttDateStart);
  deps.setGanttDateStop(snapshot.ganttDateStop);
  deps.setGanttGroupBy(snapshot.ganttGroupBy);
  deps.setGanttColor(snapshot.ganttColor);
  deps.setGanttProgress(snapshot.ganttProgress);
  deps.setGanttDefaultScale(snapshot.ganttDefaultScale);
  deps.setGanttDependencyField(snapshot.ganttDependencyField);
  deps.setGanttFields(snapshot.ganttFields);
  deps.setCohortDateStart(snapshot.cohortDateStart);
  deps.setCohortDateStop(snapshot.cohortDateStop);
  deps.setCohortInterval(snapshot.cohortInterval);
  deps.setCohortMode(snapshot.cohortMode);
  deps.setCohortTimeline(snapshot.cohortTimeline);
  deps.setCohortMeasure(snapshot.cohortMeasure);
  deps.setGridRowField(snapshot.gridRowField);
  deps.setGridColField(snapshot.gridColField);
  deps.setGridMeasure(snapshot.gridMeasure);
  deps.setGridAdjustment(snapshot.gridAdjustment);
  deps.setGridDateStart(snapshot.gridDateStart);
  deps.setGridDateStop(snapshot.gridDateStop);
  deps.setGridFields(snapshot.gridFields);
  deps.setArchOverride(snapshot.archOverride);
}
