"""World-class hospital ModuleSpec domain pack (public ORM/RPC only).

Used when NL prompts mention hospital / inpatient / wards / pharmacy / ER / ICU.
Clinic booking remains a thinner outpatient pack.
"""

from __future__ import annotations

from typing import Any


def _sel(*pairs: tuple[str, str]) -> str:
    inner = ", ".join(f"('{k}', '{v}')" for k, v in pairs)
    return f"[{inner}]"


def hospital_pack() -> dict[str, Any]:
    """Comprehensive hospital ops scaffold — depth target for 'world-class hospital' prompts."""
    gender = _sel(("male", "Male"), ("female", "Female"), ("other", "Other"), ("unknown", "Unknown"))
    blood = _sel(
        ("o_pos", "O+"),
        ("o_neg", "O-"),
        ("a_pos", "A+"),
        ("a_neg", "A-"),
        ("b_pos", "B+"),
        ("b_neg", "B-"),
        ("ab_pos", "AB+"),
        ("ab_neg", "AB-"),
        ("unknown", "Unknown"),
    )
    patient_status = _sel(
        ("registered", "Registered"),
        ("outpatient", "Outpatient"),
        ("admitted", "Admitted"),
        ("discharged", "Discharged"),
        ("deceased", "Deceased"),
    )
    specialty = _sel(
        ("general", "General Medicine"),
        ("cardiology", "Cardiology"),
        ("pediatrics", "Pediatrics"),
        ("orthopedics", "Orthopedics"),
        ("obgyn", "Obstetrics & Gynecology"),
        ("neurology", "Neurology"),
        ("oncology", "Oncology"),
        ("emergency", "Emergency Medicine"),
        ("anesthesiology", "Anesthesiology"),
        ("radiology", "Radiology"),
        ("surgery", "General Surgery"),
        ("icu", "Critical Care / ICU"),
        ("psychiatry", "Psychiatry"),
        ("other", "Other"),
    )
    appt_status = _sel(
        ("draft", "Draft"),
        ("scheduled", "Scheduled"),
        ("confirmed", "Confirmed"),
        ("checked_in", "Checked in"),
        ("in_progress", "In progress"),
        ("completed", "Completed"),
        ("no_show", "No-show"),
        ("cancelled", "Cancelled"),
    )
    encounter_type = _sel(
        ("outpatient", "Outpatient"),
        ("inpatient", "Inpatient"),
        ("emergency", "Emergency"),
        ("day_surgery", "Day surgery"),
    )
    encounter_status = _sel(
        ("open", "Open"),
        ("in_care", "In care"),
        ("awaiting_discharge", "Awaiting discharge"),
        ("discharged", "Discharged"),
        ("transferred", "Transferred"),
        ("cancelled", "Cancelled"),
    )
    bed_status = _sel(
        ("available", "Available"),
        ("occupied", "Occupied"),
        ("blocked", "Blocked"),
        ("cleaning", "Cleaning"),
        ("maintenance", "Maintenance"),
    )
    lab_status = _sel(
        ("ordered", "Ordered"),
        ("collected", "Sample collected"),
        ("processing", "Processing"),
        ("resulted", "Resulted"),
        ("cancelled", "Cancelled"),
    )
    rx_status = _sel(
        ("draft", "Draft"),
        ("prescribed", "Prescribed"),
        ("dispensed", "Dispensed"),
        ("cancelled", "Cancelled"),
    )
    surgery_status = _sel(
        ("planned", "Planned"),
        ("pre_op", "Pre-op"),
        ("in_or", "In OR"),
        ("recovery", "Recovery"),
        ("completed", "Completed"),
        ("cancelled", "Cancelled"),
    )
    pay_status = _sel(
        ("draft", "Draft"),
        ("posted", "Posted"),
        ("partial", "Partially paid"),
        ("paid", "Paid"),
        ("written_off", "Written off"),
        ("cancelled", "Cancelled"),
    )
    triage = _sel(
        ("1", "1 — Resuscitation"),
        ("2", "2 — Emergency"),
        ("3", "3 — Urgent"),
        ("4", "4 — Semi-urgent"),
        ("5", "5 — Non-urgent"),
    )
    allergy_sev = _sel(
        ("mild", "Mild"),
        ("moderate", "Moderate"),
        ("severe", "Severe"),
        ("life_threatening", "Life-threatening"),
    )

    return {
        "technical_name": "hospital_management",
        "display_name": "Hospital Management",
        "depends": ["base", "contacts", "mail"],
        "domain_pack": "hospital",
        "tags": [
            "hospital",
            "inpatient",
            "outpatient",
            "ward",
            "bed",
            "icu",
            "emergency",
            "er",
            "pharmacy",
            "laboratory",
            "radiology",
            "surgery",
            "operating",
            "theatre",
            "admission",
            "discharge",
            "encounter",
            "patient",
            "doctor",
            "nurse",
            "clinical",
            "healthcare",
            "medical",
            "triage",
            "prescription",
            "insurance",
            "billing",
        ],
        "models": [
            {
                "model": "x_department",
                "description": "Department / Service Line",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Name", "required": True},
                    {"name": "x_code", "ttype": "char", "string": "Code"},
                    {
                        "name": "x_company_id",
                        "ttype": "many2one",
                        "string": "Company",
                        "relation": "res.company",
                    },
                    {"name": "x_floor", "ttype": "char", "string": "Floor / Wing"},
                    {"name": "x_active", "ttype": "boolean", "string": "Active"},
                ],
            },
            {
                "model": "x_ward",
                "description": "Ward / Unit",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Ward Name", "required": True},
                    {"name": "x_code", "ttype": "char", "string": "Code"},
                    {
                        "name": "x_department_id",
                        "ttype": "many2one",
                        "string": "Department",
                        "relation": "x_department",
                    },
                    {
                        "name": "x_ward_type",
                        "ttype": "selection",
                        "string": "Type",
                        "selection": _sel(
                            ("general", "General"),
                            ("icu", "ICU"),
                            ("nicu", "NICU"),
                            ("maternity", "Maternity"),
                            ("pediatric", "Pediatric"),
                            ("surgical", "Surgical"),
                            ("isolation", "Isolation"),
                        ),
                    },
                    {"name": "x_capacity", "ttype": "integer", "string": "Bed Capacity"},
                    {
                        "name": "x_company_id",
                        "ttype": "many2one",
                        "string": "Company",
                        "relation": "res.company",
                    },
                ],
            },
            {
                "model": "x_bed",
                "description": "Bed",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Bed Label", "required": True},
                    {
                        "name": "x_ward_id",
                        "ttype": "many2one",
                        "string": "Ward",
                        "relation": "x_ward",
                        "required": True,
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": bed_status,
                        "required": True,
                    },
                    {"name": "x_notes", "ttype": "char", "string": "Notes"},
                ],
            },
            {
                "model": "x_doctor",
                "description": "Physician / Practitioner",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Name", "required": True},
                    {
                        "name": "x_partner_id",
                        "ttype": "many2one",
                        "string": "Contact",
                        "relation": "res.partner",
                    },
                    {
                        "name": "x_user_id",
                        "ttype": "many2one",
                        "string": "Login User",
                        "relation": "res.users",
                    },
                    {
                        "name": "x_specialty",
                        "ttype": "selection",
                        "string": "Specialty",
                        "selection": specialty,
                    },
                    {
                        "name": "x_department_id",
                        "ttype": "many2one",
                        "string": "Primary Department",
                        "relation": "x_department",
                    },
                    {"name": "x_license_no", "ttype": "char", "string": "License No."},
                    {"name": "x_active", "ttype": "boolean", "string": "Active"},
                    {
                        "name": "x_company_id",
                        "ttype": "many2one",
                        "string": "Company",
                        "relation": "res.company",
                    },
                ],
            },
            {
                "model": "x_nurse",
                "description": "Nurse / Clinical Staff",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Name", "required": True},
                    {
                        "name": "x_partner_id",
                        "ttype": "many2one",
                        "string": "Contact",
                        "relation": "res.partner",
                    },
                    {
                        "name": "x_ward_id",
                        "ttype": "many2one",
                        "string": "Home Ward",
                        "relation": "x_ward",
                    },
                    {"name": "x_shift", "ttype": "char", "string": "Default Shift"},
                    {"name": "x_active", "ttype": "boolean", "string": "Active"},
                    {
                        "name": "x_company_id",
                        "ttype": "many2one",
                        "string": "Company",
                        "relation": "res.company",
                    },
                ],
            },
            {
                "model": "x_patient",
                "description": "Patient",
                "mode": "new",
                "is_workflow": True,
                "mixins": ["mail.thread", "mail.activity.mixin"],
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Full Name", "required": True},
                    {
                        "name": "x_code",
                        "ttype": "char",
                        "string": "MRN",
                        "help": "Medical record number — wire ir.sequence (e.g. MRN/00001)",
                    },
                    {
                        "name": "x_partner_id",
                        "ttype": "many2one",
                        "string": "Contact",
                        "relation": "res.partner",
                    },
                    {
                        "name": "x_gender",
                        "ttype": "selection",
                        "string": "Gender",
                        "selection": gender,
                    },
                    {"name": "x_dob", "ttype": "date", "string": "Date of Birth"},
                    {
                        "name": "x_blood_type",
                        "ttype": "selection",
                        "string": "Blood Type",
                        "selection": blood,
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": patient_status,
                        "required": True,
                    },
                    {
                        "name": "x_primary_doctor_id",
                        "ttype": "many2one",
                        "string": "Primary Physician",
                        "relation": "x_doctor",
                    },
                    {
                        "name": "x_emergency_contact_id",
                        "ttype": "many2one",
                        "string": "Emergency Contact",
                        "relation": "res.partner",
                    },
                    {"name": "x_national_id", "ttype": "char", "string": "National ID"},
                    {"name": "x_notes", "ttype": "text", "string": "Alerts / Notes"},
                    {
                        "name": "x_company_id",
                        "ttype": "many2one",
                        "string": "Company",
                        "relation": "res.company",
                    },
                ],
            },
            {
                "model": "x_allergy",
                "description": "Allergy / Intolerance",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Allergen", "required": True},
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_severity",
                        "ttype": "selection",
                        "string": "Severity",
                        "selection": allergy_sev,
                    },
                    {"name": "x_reaction", "ttype": "char", "string": "Reaction"},
                    {"name": "x_active", "ttype": "boolean", "string": "Active"},
                ],
            },
            {
                "model": "x_appointment",
                "description": "Outpatient Appointment",
                "mode": "new",
                "is_workflow": True,
                "mixins": ["mail.thread", "mail.activity.mixin"],
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Subject", "required": True},
                    {
                        "name": "x_code",
                        "ttype": "char",
                        "string": "Reference",
                        "help": "Appointment reference — wire ir.sequence (e.g. APT/00001)",
                    },
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_doctor_id",
                        "ttype": "many2one",
                        "string": "Doctor",
                        "relation": "x_doctor",
                        "required": True,
                    },
                    {
                        "name": "x_department_id",
                        "ttype": "many2one",
                        "string": "Department",
                        "relation": "x_department",
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": appt_status,
                        "required": True,
                    },
                    {"name": "x_start", "ttype": "datetime", "string": "Start", "required": True},
                    {"name": "x_end", "ttype": "datetime", "string": "End"},
                    {"name": "x_reason", "ttype": "char", "string": "Chief Complaint"},
                    {
                        "name": "x_company_id",
                        "ttype": "many2one",
                        "string": "Company",
                        "relation": "res.company",
                    },
                ],
            },
            {
                "model": "x_encounter",
                "description": "Encounter / Admission",
                "mode": "new",
                "is_workflow": True,
                "mixins": ["mail.thread", "mail.activity.mixin"],
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Label", "required": True},
                    {
                        "name": "x_code",
                        "ttype": "char",
                        "string": "Encounter No.",
                        "help": "Encounter / admission number — wire ir.sequence (e.g. ENC/00001)",
                    },
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_attending_doctor_id",
                        "ttype": "many2one",
                        "string": "Attending Physician",
                        "relation": "x_doctor",
                    },
                    {
                        "name": "x_type",
                        "ttype": "selection",
                        "string": "Type",
                        "selection": encounter_type,
                        "required": True,
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": encounter_status,
                        "required": True,
                    },
                    {
                        "name": "x_triage",
                        "ttype": "selection",
                        "string": "Triage",
                        "selection": triage,
                    },
                    {
                        "name": "x_ward_id",
                        "ttype": "many2one",
                        "string": "Ward",
                        "relation": "x_ward",
                    },
                    {
                        "name": "x_bed_id",
                        "ttype": "many2one",
                        "string": "Bed",
                        "relation": "x_bed",
                    },
                    {"name": "x_admit_datetime", "ttype": "datetime", "string": "Admit"},
                    {"name": "x_discharge_datetime", "ttype": "datetime", "string": "Discharge"},
                    {"name": "x_chief_complaint", "ttype": "text", "string": "Chief Complaint"},
                    {
                        "name": "x_company_id",
                        "ttype": "many2one",
                        "string": "Company",
                        "relation": "res.company",
                    },
                ],
            },
            {
                "model": "x_vital_sign",
                "description": "Vital Signs",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Label", "required": True},
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_encounter_id",
                        "ttype": "many2one",
                        "string": "Encounter",
                        "relation": "x_encounter",
                    },
                    {"name": "x_taken_at", "ttype": "datetime", "string": "Taken At", "required": True},
                    {"name": "x_pulse", "ttype": "integer", "string": "Pulse (bpm)"},
                    {"name": "x_bp_systolic", "ttype": "integer", "string": "BP Systolic"},
                    {"name": "x_bp_diastolic", "ttype": "integer", "string": "BP Diastolic"},
                    {"name": "x_temp_c", "ttype": "float", "string": "Temp °C"},
                    {"name": "x_spo2", "ttype": "integer", "string": "SpO2 %"},
                    {"name": "x_resp_rate", "ttype": "integer", "string": "Resp. Rate"},
                    {
                        "name": "x_nurse_id",
                        "ttype": "many2one",
                        "string": "Recorded By",
                        "relation": "x_nurse",
                    },
                ],
            },
            {
                "model": "x_medical_record",
                "description": "Clinical Note / Chart Entry",
                "mode": "new",
                "mixins": ["mail.thread"],
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Title", "required": True},
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_encounter_id",
                        "ttype": "many2one",
                        "string": "Encounter",
                        "relation": "x_encounter",
                    },
                    {
                        "name": "x_doctor_id",
                        "ttype": "many2one",
                        "string": "Author",
                        "relation": "x_doctor",
                    },
                    {"name": "x_note_datetime", "ttype": "datetime", "string": "Note Time"},
                    {"name": "x_diagnosis", "ttype": "text", "string": "Diagnosis / ICD notes"},
                    {"name": "x_soap_subjective", "ttype": "text", "string": "SOAP — Subjective"},
                    {"name": "x_soap_objective", "ttype": "text", "string": "SOAP — Objective"},
                    {"name": "x_soap_assessment", "ttype": "text", "string": "SOAP — Assessment"},
                    {"name": "x_soap_plan", "ttype": "text", "string": "SOAP — Plan"},
                    {"name": "x_treatment_plan", "ttype": "text", "string": "Treatment Plan"},
                ],
            },
            {
                "model": "x_lab_order",
                "description": "Laboratory Order",
                "mode": "new",
                "is_workflow": True,
                "mixins": ["mail.thread", "mail.activity.mixin"],
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Test / Panel", "required": True},
                    {
                        "name": "x_code",
                        "ttype": "char",
                        "string": "Order No.",
                        "help": "Lab order reference — wire ir.sequence (e.g. LAB/00001)",
                    },
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_encounter_id",
                        "ttype": "many2one",
                        "string": "Encounter",
                        "relation": "x_encounter",
                    },
                    {
                        "name": "x_ordering_doctor_id",
                        "ttype": "many2one",
                        "string": "Ordering Physician",
                        "relation": "x_doctor",
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": lab_status,
                        "required": True,
                    },
                    {"name": "x_ordered_at", "ttype": "datetime", "string": "Ordered At"},
                    {"name": "x_result_summary", "ttype": "text", "string": "Result Summary"},
                    {"name": "x_resulted_at", "ttype": "datetime", "string": "Resulted At"},
                ],
            },
            {
                "model": "x_imaging_order",
                "description": "Imaging / Radiology Order",
                "mode": "new",
                "is_workflow": True,
                "mixins": ["mail.thread", "mail.activity.mixin"],
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Study", "required": True},
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_encounter_id",
                        "ttype": "many2one",
                        "string": "Encounter",
                        "relation": "x_encounter",
                    },
                    {
                        "name": "x_modality",
                        "ttype": "selection",
                        "string": "Modality",
                        "selection": _sel(
                            ("xray", "X-Ray"),
                            ("ct", "CT"),
                            ("mri", "MRI"),
                            ("ultrasound", "Ultrasound"),
                            ("other", "Other"),
                        ),
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": lab_status,
                        "required": True,
                    },
                    {
                        "name": "x_ordering_doctor_id",
                        "ttype": "many2one",
                        "string": "Ordering Physician",
                        "relation": "x_doctor",
                    },
                    {"name": "x_findings", "ttype": "text", "string": "Findings"},
                ],
            },
            {
                "model": "x_prescription",
                "description": "Prescription",
                "mode": "new",
                "is_workflow": True,
                "mixins": ["mail.thread", "mail.activity.mixin"],
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Label", "required": True},
                    {
                        "name": "x_code",
                        "ttype": "char",
                        "string": "Rx No.",
                        "help": "Prescription number — wire ir.sequence (e.g. RX/00001)",
                    },
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_doctor_id",
                        "ttype": "many2one",
                        "string": "Prescriber",
                        "relation": "x_doctor",
                        "required": True,
                    },
                    {
                        "name": "x_encounter_id",
                        "ttype": "many2one",
                        "string": "Encounter",
                        "relation": "x_encounter",
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": rx_status,
                        "required": True,
                    },
                    {"name": "x_prescribed_at", "ttype": "datetime", "string": "Prescribed At"},
                    {"name": "x_notes", "ttype": "text", "string": "Pharmacy Notes"},
                ],
            },
            {
                "model": "x_prescription_line",
                "description": "Prescription Line",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Medication", "required": True},
                    {
                        "name": "x_prescription_id",
                        "ttype": "many2one",
                        "string": "Prescription",
                        "relation": "x_prescription",
                        "required": True,
                    },
                    {"name": "x_dose", "ttype": "char", "string": "Dose"},
                    {"name": "x_route", "ttype": "char", "string": "Route"},
                    {"name": "x_frequency", "ttype": "char", "string": "Frequency"},
                    {"name": "x_duration_days", "ttype": "integer", "string": "Duration (days)"},
                    {"name": "x_qty", "ttype": "float", "string": "Quantity"},
                ],
            },
            {
                "model": "x_surgery",
                "description": "Surgery / Procedure",
                "mode": "new",
                "is_workflow": True,
                "mixins": ["mail.thread", "mail.activity.mixin"],
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Procedure", "required": True},
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_encounter_id",
                        "ttype": "many2one",
                        "string": "Encounter",
                        "relation": "x_encounter",
                    },
                    {
                        "name": "x_surgeon_id",
                        "ttype": "many2one",
                        "string": "Surgeon",
                        "relation": "x_doctor",
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": surgery_status,
                        "required": True,
                    },
                    {"name": "x_scheduled_start", "ttype": "datetime", "string": "Scheduled Start"},
                    {"name": "x_or_room", "ttype": "char", "string": "OR / Theatre"},
                    {"name": "x_notes", "ttype": "text", "string": "Operative Notes"},
                ],
            },
            {
                "model": "x_insurance",
                "description": "Patient Insurance Cover",
                "mode": "new",
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Plan / Payer", "required": True},
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {"name": "x_policy_no", "ttype": "char", "string": "Policy No."},
                    {"name": "x_valid_from", "ttype": "date", "string": "Valid From"},
                    {"name": "x_valid_to", "ttype": "date", "string": "Valid To"},
                    {
                        "name": "x_payer_id",
                        "ttype": "many2one",
                        "string": "Payer Contact",
                        "relation": "res.partner",
                    },
                ],
            },
            {
                "model": "x_payment",
                "description": "Patient Charge / Payment",
                "mode": "new",
                "is_workflow": True,
                "fields": [
                    {"name": "x_name", "ttype": "char", "string": "Description", "required": True},
                    {
                        "name": "x_code",
                        "ttype": "char",
                        "string": "Reference",
                        "help": "Billing reference — wire ir.sequence (e.g. INV/00001)",
                    },
                    {
                        "name": "x_patient_id",
                        "ttype": "many2one",
                        "string": "Patient",
                        "relation": "x_patient",
                        "required": True,
                    },
                    {
                        "name": "x_encounter_id",
                        "ttype": "many2one",
                        "string": "Encounter",
                        "relation": "x_encounter",
                    },
                    {"name": "x_amount", "ttype": "float", "string": "Amount", "required": True},
                    {
                        "name": "x_currency_id",
                        "ttype": "many2one",
                        "string": "Currency",
                        "relation": "res.currency",
                    },
                    {
                        "name": "x_status",
                        "ttype": "selection",
                        "string": "Status",
                        "selection": pay_status,
                        "required": True,
                    },
                    {"name": "x_date", "ttype": "date", "string": "Date"},
                    {
                        "name": "x_company_id",
                        "ttype": "many2one",
                        "string": "Company",
                        "relation": "res.company",
                    },
                ],
            },
        ],
        "smart_buttons": [
            {
                "on_model": "x_patient",
                "label": "Appointments",
                "related_model": "x_appointment",
                "relation_field": "x_patient_id",
                "icon": "fa-calendar",
            },
            {
                "on_model": "x_patient",
                "label": "Encounters",
                "related_model": "x_encounter",
                "relation_field": "x_patient_id",
                "icon": "fa-hospital-o",
            },
            {
                "on_model": "x_patient",
                "label": "Notes",
                "related_model": "x_medical_record",
                "relation_field": "x_patient_id",
                "icon": "fa-stethoscope",
            },
            {
                "on_model": "x_patient",
                "label": "Allergies",
                "related_model": "x_allergy",
                "relation_field": "x_patient_id",
                "icon": "fa-exclamation-triangle",
            },
            {
                "on_model": "x_patient",
                "label": "Vitals",
                "related_model": "x_vital_sign",
                "relation_field": "x_patient_id",
                "icon": "fa-heartbeat",
            },
            {
                "on_model": "x_patient",
                "label": "Labs",
                "related_model": "x_lab_order",
                "relation_field": "x_patient_id",
                "icon": "fa-flask",
            },
            {
                "on_model": "x_patient",
                "label": "Imaging",
                "related_model": "x_imaging_order",
                "relation_field": "x_patient_id",
                "icon": "fa-picture-o",
            },
            {
                "on_model": "x_patient",
                "label": "Rx",
                "related_model": "x_prescription",
                "relation_field": "x_patient_id",
                "icon": "fa-medkit",
            },
            {
                "on_model": "x_patient",
                "label": "Surgeries",
                "related_model": "x_surgery",
                "relation_field": "x_patient_id",
                "icon": "fa-scissors",
            },
            {
                "on_model": "x_patient",
                "label": "Billing",
                "related_model": "x_payment",
                "relation_field": "x_patient_id",
                "icon": "fa-money",
            },
            {
                "on_model": "x_patient",
                "label": "Insurance",
                "related_model": "x_insurance",
                "relation_field": "x_patient_id",
                "icon": "fa-shield",
            },
            {
                "on_model": "x_doctor",
                "label": "Appointments",
                "related_model": "x_appointment",
                "relation_field": "x_doctor_id",
                "icon": "fa-calendar",
            },
            {
                "on_model": "x_ward",
                "label": "Beds",
                "related_model": "x_bed",
                "relation_field": "x_ward_id",
                "icon": "fa-bed",
            },
            {
                "on_model": "x_encounter",
                "label": "Vitals",
                "related_model": "x_vital_sign",
                "relation_field": "x_encounter_id",
                "icon": "fa-heartbeat",
            },
            {
                "on_model": "x_prescription",
                "label": "Lines",
                "related_model": "x_prescription_line",
                "relation_field": "x_prescription_id",
                "icon": "fa-list",
            },
            {
                "on_model": "res.partner",
                "label": "Patient",
                "related_model": "x_patient",
                "relation_field": "x_partner_id",
                "icon": "fa-user",
                "requires_inherit_view": True,
                "note": "Applied as inherit on Contacts button_box",
            },
            {
                "on_model": "res.partner",
                "label": "Doctor",
                "related_model": "x_doctor",
                "relation_field": "x_partner_id",
                "icon": "fa-user-md",
                "requires_inherit_view": True,
                "note": "Applied as inherit on Contacts button_box",
            },
        ],
        "automations": [
            {
                "name": "Activity: confirm new appointment",
                "model": "x_appointment",
                "trigger": "on_create",
                "description": "Create follow-up activity when appointment is booked",
                "safe_actions": [
                    {
                        "kind": "next_activity",
                        "summary": "Confirm appointment with patient",
                    }
                ],
            },
            {
                "name": "Mark patient admitted on inpatient encounter",
                "model": "x_encounter",
                "trigger": "on_create_or_write",
                "description": "When encounter is inpatient/open → patient status admitted",
                "filter_domain": (
                    "[('x_type', '=', 'inpatient'), ('x_status', 'in', ['open', 'in_care'])]"
                ),
                "safe_actions": [
                    {
                        "kind": "related_write",
                        "relation_field": "x_patient_id",
                        "field": "x_status",
                        "value": "admitted",
                    }
                ],
            },
            {
                "name": "Mark patient discharged on encounter discharge",
                "model": "x_encounter",
                "trigger": "on_write",
                "description": "When encounter discharged → patient discharged",
                "filter_domain": "[('x_status', '=', 'discharged')]",
                "safe_actions": [
                    {
                        "kind": "related_write",
                        "relation_field": "x_patient_id",
                        "field": "x_status",
                        "value": "discharged",
                    }
                ],
            },
            {
                "name": "Occupy bed on admit",
                "model": "x_encounter",
                "trigger": "on_write",
                "description": "When bed assigned and encounter open → bed occupied",
                "filter_domain": "[('x_bed_id', '!=', False), ('x_status', '=', 'in_care')]",
                "safe_actions": [
                    {
                        "kind": "related_write",
                        "relation_field": "x_bed_id",
                        "field": "x_status",
                        "value": "occupied",
                    }
                ],
            },
            {
                "name": "Lab result follow-up",
                "model": "x_lab_order",
                "trigger": "on_write",
                "description": "Activity when lab resulted",
                "filter_domain": "[('x_status', '=', 'resulted')]",
                "safe_actions": [
                    {
                        "kind": "next_activity",
                        "summary": "Review lab results with patient",
                    }
                ],
            },
        ],
        "reuse_hints": [
            {
                "model": "res.partner",
                "reason": "Patients, doctors, nurses, emergency contacts, and payers as Contacts",
            },
            {
                "model": "res.users",
                "reason": "Map clinicians to login users for assignment / activities",
            },
            {
                "model": "res.company",
                "reason": "Multi-hospital / multi-company isolation via x_company_id",
            },
            {
                "model": "res.currency",
                "reason": "Billing amounts",
            },
            {
                "model": "account.move",
                "reason": "Optional later: formal invoices from x_payment (accounting stub)",
                "optional": True,
            },
        ],
    }


__all__ = ["hospital_pack"]
