"""baseline

Revision ID: 65cd29676b8f
Revises: 
Create Date: 2026-08-03 15:32:01.140188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cd29676b8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_app_api_keys_key_prefix'), 'app_api_keys', ['key_prefix'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_path'), 'audit_logs', ['path'], unique=False)
    op.create_table('expert_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('breadcrumb', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_chunks_content_hash'), 'expert_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_expert_chunks_source'), 'expert_chunks', ['source'], unique=False)
    op.create_index(op.f('ix_expert_chunks_version'), 'expert_chunks', ['version'], unique=False)
    op.create_table('odoo_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('db_name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('server_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen_version', sa.String(length=50), nullable=True),
    sa.Column('upgrade_detected', sa.Boolean(), nullable=False),
    sa.Column('upgrade_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preview_theme_json', sa.Text(), nullable=True),
    sa.Column('protected_manifest_json', sa.Text(), nullable=True),
    sa.Column('protected_manifest_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_model', sa.String(length=200), nullable=False),
    sa.Column('button_method', sa.String(length=200), nullable=False),
    sa.Column('button_label', sa.String(length=200), nullable=True),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.Column('odoo_wrapper_action_id', sa.Integer(), nullable=True),
    sa.Column('odoo_view_inherit_id', sa.Integer(), nullable=True),
    sa.Column('odoo_studio_rule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_rules_connection_id'), 'approval_rules', ['connection_id'], unique=False)
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_connection_id'), 'background_jobs', ['connection_id'], unique=False)
    op.create_table('bulk_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('dry_run', sa.String(length=5), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_runs_connection_id'), 'bulk_runs', ['connection_id'], unique=False)
    op.create_table('customization_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customization_projects_connection_id'), 'customization_projects', ['connection_id'], unique=False)
    op.create_table('env_pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('staging_connection_id', sa.String(length=36), nullable=False),
    sa.Column('prod_connection_id', sa.String(length=36), nullable=False),
    sa.Column('sandbox_connection_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prod_connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sandbox_connection_id'], ['odoo_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staging_connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_env_pipelines_prod_connection_id'), 'env_pipelines', ['prod_connection_id'], unique=False)
    op.create_index(op.f('ix_env_pipelines_staging_connection_id'), 'env_pipelines', ['staging_connection_id'], unique=False)
    op.create_table('health_check_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('previous_version', sa.String(length=50), nullable=True),
    sa.Column('current_version', sa.String(length=50), nullable=True),
    sa.Column('ok_count', sa.Integer(), nullable=False),
    sa.Column('broken_count', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_check_runs_connection_id'), 'health_check_runs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_health_check_runs_job_id'), 'health_check_runs', ['job_id'], unique=False)
    op.create_table('metadata_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_key', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('reversible', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_snapshots_connection_id'), 'metadata_snapshots', ['connection_id'], unique=False)
    op.create_table('promoted_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('module_name', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('zip_sha256', sa.String(length=64), nullable=True),
    sa.Column('models_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promoted_modules_connection_id'), 'promoted_modules', ['connection_id'], unique=False)
    op.create_index(op.f('ix_promoted_modules_module_name'), 'promoted_modules', ['module_name'], unique=False)
    op.create_table('sandbox_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('module_name', sa.String(length=120), nullable=False),
    sa.Column('zip_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_validations_connection_id'), 'sandbox_validations', ['connection_id'], unique=False)
    op.create_table('approval_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('record_model', sa.String(length=200), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['odoo_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['approval_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_entries_connection_id'), 'approval_entries', ['connection_id'], unique=False)
    op.create_index(op.f('ix_approval_entries_rule_id'), 'approval_entries', ['rule_id'], unique=False)
    op.create_table('pipeline_hops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('hop', sa.String(length=20), nullable=False),
    sa.Column('module_name', sa.String(length=120), nullable=False),
    sa.Column('zip_sha256', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.Column('validation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['env_pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_hops_pipeline_id'), 'pipeline_hops', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_hops_zip_sha256'), 'pipeline_hops', ['zip_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_hops_zip_sha256'), table_name='pipeline_hops')
    op.drop_index(op.f('ix_pipeline_hops_pipeline_id'), table_name='pipeline_hops')
    op.drop_table('pipeline_hops')
    op.drop_index(op.f('ix_approval_entries_rule_id'), table_name='approval_entries')
    op.drop_index(op.f('ix_approval_entries_connection_id'), table_name='approval_entries')
    op.drop_table('approval_entries')
    op.drop_index(op.f('ix_sandbox_validations_connection_id'), table_name='sandbox_validations')
    op.drop_table('sandbox_validations')
    op.drop_index(op.f('ix_promoted_modules_module_name'), table_name='promoted_modules')
    op.drop_index(op.f('ix_promoted_modules_connection_id'), table_name='promoted_modules')
    op.drop_table('promoted_modules')
    op.drop_index(op.f('ix_metadata_snapshots_connection_id'), table_name='metadata_snapshots')
    op.drop_table('metadata_snapshots')
    op.drop_index(op.f('ix_health_check_runs_job_id'), table_name='health_check_runs')
    op.drop_index(op.f('ix_health_check_runs_connection_id'), table_name='health_check_runs')
    op.drop_table('health_check_runs')
    op.drop_index(op.f('ix_env_pipelines_staging_connection_id'), table_name='env_pipelines')
    op.drop_index(op.f('ix_env_pipelines_prod_connection_id'), table_name='env_pipelines')
    op.drop_table('env_pipelines')
    op.drop_index(op.f('ix_customization_projects_connection_id'), table_name='customization_projects')
    op.drop_table('customization_projects')
    op.drop_index(op.f('ix_bulk_runs_connection_id'), table_name='bulk_runs')
    op.drop_table('bulk_runs')
    op.drop_index(op.f('ix_background_jobs_connection_id'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_approval_rules_connection_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    op.drop_table('odoo_connections')
    op.drop_index(op.f('ix_expert_chunks_version'), table_name='expert_chunks')
    op.drop_index(op.f('ix_expert_chunks_source'), table_name='expert_chunks')
    op.drop_index(op.f('ix_expert_chunks_content_hash'), table_name='expert_chunks')
    op.drop_table('expert_chunks')
    op.drop_index(op.f('ix_audit_logs_path'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_api_keys_key_prefix'), table_name='app_api_keys')
    op.drop_table('app_api_keys')
    # ### end Alembic commands ###
