"""Generated-module README trust artifact (PROD-2 / Doc 1 Phase 8)."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from module_generator import ModuleSpec


def render_module_readme(spec: "ModuleSpec", *, odoo_major: int = 19) -> str:
    """README.md shipped inside every generated addon zip."""
    models = [m.model for m in (spec.models or []) if getattr(m, "model", None)]
    depends = ", ".join(spec.depends or ["base"])
    lines = [
        f"# {spec.display_name or spec.technical_name}",
        "",
        "Generated by the **No-Code Odoo Customization Platform** — a hand-off artifact",
        "for your Odoo administrator or developer.",
        "",
        "## What was generated",
        "",
        f"- Technical name: `{spec.technical_name}`",
        f"- Target Odoo series: **{odoo_major}.0** (manifest `{odoo_major}.0.1.0.0`)",
        f"- Depends: `{depends}`",
        f"- Custom models: {', '.join(f'`{m}`' for m in models) if models else '*(inherit/extensions only)*'}",
        f"- Views: {len(spec.views or [])} · Menus: {len(spec.menus or [])} · "
        f"Automations: {len(spec.python_automations or [])}",
        "",
        "## Install steps (by hosting tier)",
        "",
        "| Tier | Steps |",
        "|------|-------|",
        "| **Self-hosted / Docker / on-prem** | Copy the module folder into your addons path → "
        "update Apps list → Install. Run sandbox validation before production. |",
        "| **Odoo.sh** | Push to your development branch → let the build run → "
        "install on staging → promote after tests. |",
        "| **Odoo Online (SaaS)** | Import via supported Apps packaging flow only; "
        "Python modules require Odoo-approved distribution — see tier gating in the builder. |",
        "",
        "## Module contents map",
        "",
        "| Path | Purpose |",
        "|------|---------|",
        "| `__manifest__.py` | Module metadata and data file load order |",
        "| `models/` | Python model definitions (when install_mode=python) |",
        "| `views/` | Form/list/search/kanban XML |",
        "| `security/` | Access CSV + record rules |",
        "| `data/` | Sequences, automations, mail templates |",
        "| `.meta.json` | Machine-readable ModuleSpec sidecar (reverse import) |",
        "",
        "## Hand to your developer",
        "",
        "This module was produced from a no-code specification. Before production:",
        "",
        "1. **Review** security rules and server actions — especially anything marked advanced.",
        "2. **Test** on a staging database matching your Odoo major version.",
        "3. **Diff** against your change-control policy; treat `.meta.json` as the source spec.",
        "4. **Rollback**: keep a database backup; metadata snapshots in the builder can restore",
        "   views/automations where Odoo allows.",
        "",
        "Questions about ERP impact belong with your functional owner — this README documents",
        "what the generator emitted, not your business sign-off.",
        "",
    ]
    return "\n".join(lines) + "\n"
